name: Sync Files from Source Repo

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        
      - name: Clone source repository
        run: |
          git clone https://github.com/cmliu/edgetunnel.git temp_repo
          
      - name: Copy and rename files
        run: |
          mkdir -p src
          cp temp_repo/_worker.js src/index.js
          cp temp_repo/明文源码.js src/source.js
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/
          git commit -m "chore: sync files from source repository" || exit 0
          git push